[package]
name = "cat-litter-reminder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart-leds = "0.3.0"
ws281x-rpi = "0.0.1"
chrono = "0.4.22"
tokio-cron-scheduler = "0.8.1"